### ISSUE TITLE
Make it easier to find these samples

### ISSUE THREAD

**Issue by CIPop** [microsoft/Windows-classic-samples#7]
- [ ] Under the Microsoft GH account, if I search for "samples" these appear on the second page. Maybe we can have a single Samples location that is indexed and searchable by API/component name?
- [ ] The project name should be searchable by "Win32" as well.
- [ ] PSDK links in MSDN should point to this repo. (E.g. https://msdn.microsoft.com/en-us/library/windows/desktop/aa378828(v=vs.85).aspx)

**Comment by oldnewthing** [comment]
The problem is that there is no consistent metadata for the samples in this repo, since they were for the most part just cobbled together from old SDKs. If you're willing to generate the metadata for the 1000+ samples in this repo, here's the template:

```yaml
---
page_type: sample
languages:
- csharp
- cpp
- cppwinrt
 - (etc)
products:
- windows
urlFragment: (short-unique-name-for-sample)
---

# TITLE sample

DESCRIPTION.
```

Put this at the top of the README.md file for each sample you want to be indexed.
